In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import HIAforQMiFI as funcs
import numpy as np

In [2]:
data = pd.read_excel('LW_monthly_1972-2024.xlsx')

In [3]:
data.head()

Unnamed: 0  Unnamed: 1         1         2         3         4         5  \
0        1972           1  0.031598  0.032547  0.033557  0.034558  0.035502   
1        1972           2  0.031713  0.032907  0.034075  0.035181  0.036203   
2        1972           3  0.034877  0.036851  0.038742  0.040475  0.042002   
3        1972           4  0.033780  0.034820  0.035986  0.037184  0.038345   
4        1972           5  0.035883  0.036840  0.037882  0.038929  0.039930   

          6         7         8  ...       111       112       113       114  \
0  0.036368  0.037163  0.037911  ...  0.060441  0.060476  0.060512  0.060547   
1  0.037143  0.038022  0.038869  ...  0.059898  0.059926  0.059951  0.059976   
2  0.043324  0.044480  0.045518  ...  0.060521  0.060511  0.060501  0.060490   
3  0.039438  0.040458  0.041405  ...  0.061130  0.061170  0.061208  0.061246   
4  0.040863  0.041725  0.042519  ...  0.060647  0.060693  0.060737  0.060780   

        115       116       117       118       119       120  
0  0.060583  0.060619  0.060656  0.060693  0.060731  0.060769  
1  0.059998  0.060019  0.060038  0.060056  0.060072  0.060086  
2  0.060479  0.060467  0.060455  0.060443  0.060430  0.060416  
3  0.061282  0.061318  0.061352  0.061385  0.061417  0.061447  
4  0.060822  0.060863  0.060902  0.060940  0.060976  0.061011  

[5 rows x 122 columns]

In [4]:
data.iloc[:, 120+1].mean().item()

0.05935553343927729

In [5]:
data = data.iloc[:, 2:]
data.index = range(1, len(data)+1)

In [6]:
data.T

1         2         3         4         5         6         7    \
1    0.031598  0.031713  0.034877  0.033780  0.035883  0.037318  0.036495   
2    0.032547  0.032907  0.036851  0.034820  0.036840  0.039034  0.037383   
3    0.033557  0.034075  0.038742  0.035986  0.037882  0.040760  0.038435   
4    0.034558  0.035181  0.040475  0.037184  0.038929  0.042429  0.039595   
5    0.035502  0.036203  0.042002  0.038345  0.039930  0.043986  0.040802   
..        ...       ...       ...       ...       ...       ...       ...   
116  0.060619  0.060019  0.060467  0.061318  0.060863  0.060046  0.061518   
117  0.060656  0.060038  0.060455  0.061352  0.060902  0.060031  0.061540   
118  0.060693  0.060056  0.060443  0.061385  0.060940  0.060014  0.061560   
119  0.060731  0.060072  0.060430  0.061417  0.060976  0.059996  0.061580   
120  0.060769  0.060086  0.060416  0.061447  0.061011  0.059978  0.061598   

          8         9         10   ...       627       628       629  \
1    0.043125  0.045016  0.045448  ...  0.052643  0.053411  0.052973   
2    0.044140  0.046309  0.046607  ...  0.052512  0.053384  0.052960   
3    0.045245  0.047648  0.047769  ...  0.052328  0.053310  0.052885   
4    0.046391  0.048958  0.048869  ...  0.052095  0.053198  0.052755   
5    0.047525  0.050161  0.049846  ...  0.051821  0.053056  0.052579   
..        ...       ...       ...  ...       ...       ...       ...   
116  0.063124  0.064415  0.063169  ...  0.041389  0.046035  0.044359   
117  0.063159  0.064463  0.063202  ...  0.041366  0.046008  0.044342   
118  0.063196  0.064509  0.063235  ...  0.041342  0.045980  0.044323   
119  0.063234  0.064553  0.063268  ...  0.041317  0.045951  0.044305   
120  0.063273  0.064597  0.063300  ...  0.041290  0.045921  0.044286   

          630       631       632       633       634       635       636  
1    0.052852  0.053336  0.051834  0.046387  0.045010  0.043269  0.041557  
2    0.052797  0.052726  0.050873  0.045805  0.044884  0.043328  0.041594  
3    0.052687  0.052080  0.049923  0.045145  0.044685  0.043339  0.041629  
4    0.052530  0.051423  0.048997  0.044433  0.044437  0.043314  0.041660  
5    0.052333  0.050773  0.048106  0.043694  0.044166  0.043268  0.041686  
..        ...       ...       ...       ...       ...       ...       ...  
116  0.043339  0.039793  0.038635  0.037508  0.042340  0.041279  0.045358  
117  0.043327  0.039793  0.038640  0.037516  0.042337  0.041275  0.045362  
118  0.043314  0.039793  0.038642  0.037522  0.042332  0.041269  0.045366  
119  0.043300  0.039791  0.038641  0.037527  0.042327  0.041263  0.045369  
120  0.043286  0.039789  0.038639  0.037531  0.042321  0.041257  0.045372  

[120 rows x 636 columns]

In [7]:
lamba = 0.0609

In [8]:
tau = np.arange(1, 121)
B = np.stack([np.ones_like(tau),
                (1 - np.exp(-lamba * tau))/(lamba * tau),
                    (1 - np.exp(-lamba * tau))/(lamba * tau) - np.exp(-lamba * tau)], axis=1)

In [9]:
B.shape

(120, 3)

In [10]:
y = np.asarray(data.T)         

In [11]:
y.shape

(120, 636)

In [12]:
i = 25


# estimate the beta parameters using data up to time i
y_slice = y[:, :i]          

In [13]:
model = LinearRegression(fit_intercept=False)
model.fit(B, y_slice)

LinearRegression(fit_intercept=False)

In [14]:
B[12-1, :].reshape(-1, 1)

array([[1.        ],
       [0.70946413],
       [0.22794051]])

In [15]:
model.coef_[:,0]

array([0.06495578, 0.06451958, 0.06044101, 0.06397247, 0.0644753 ,
       0.06062372, 0.06346521, 0.06454719, 0.06540123, 0.0640006 ,
       0.06352071, 0.06319276, 0.06284267, 0.06221369, 0.06262618,
       0.06466954, 0.06773546, 0.06675643, 0.06669619, 0.06787071,
       0.06746337, 0.06614309, 0.06721012, 0.06801068, 0.07157938])

In [16]:
beta = {
        1 : [],
        2 : [],
        3: []
    }
# estimate beta parameters for each time t in the sample up to i
for t in range(i):    
    model = LinearRegression(fit_intercept=False)
    model.fit(B, y_slice[:,t])
    beta[1].append(model.coef_[0].item())
    beta[2].append(model.coef_[1].item())
    beta[3].append(model.coef_[2].item())

In [17]:
beta = {k: np.array(v).reshape(-1, 1) for k, v in beta.items()}

In [18]:

ar_beta1 = LinearRegression(fit_intercept=True)
ar_beta1.fit(beta[1][0:i-1], beta[1][1:i])
ar_beta2 = LinearRegression(fit_intercept=True)
ar_beta2.fit(beta[2][0:i-1], beta[2][1:i])
ar_beta3 = LinearRegression(fit_intercept=True)
ar_beta3.fit(beta[3][0:i-1], beta[3][1:i])

LinearRegression()

In [19]:
def recursive_forecast(model, last_known_value, h):
    # Ensure input is 2D (1, 1) for sklearn
    current_val = last_known_value.reshape(1, -1)
    
    for _ in range(h):
        current_val = model.predict(current_val)
        
    return current_val[0, 0].item()

In [20]:
print(funcs.getNelsonSiegelForecast(120, 1, 12))

0.12679953620237164


In [21]:
j = 25

In [22]:
data = pd.read_excel('LW_monthly_1972-2024.xlsx')           # Load the data
data = data.iloc[:, 2:]                                     # Remove year and month columns                  
data.index = range(1, len(data)+1)                          # Reset index to start from 1


y = data[j - 1].shift(-1) - data[j]                             # shape (635,)
X = (data[j] - data[1]) / (j - 1)                               # shape (635,)

In [23]:
# fit the regression model
valid_idx = ~np.isnan(y) & ~np.isnan(X)
y_clean = y[valid_idx].values.reshape(-1, 1)
X_clean = X[valid_idx].values.reshape(-1, 1)
model = LinearRegression(fit_intercept=True)
model.fit(X_clean, y_clean)

LinearRegression()

In [24]:
model.coef_, model.intercept_   

(array([[-1.05517251]]), array([0.00016422]))

In [25]:
funcs.getEHtest(60)

-0.15333817871809247